/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BingoBoard: typeof import('./components/BingoBoard.vue')['default']
    BingoTile: typeof import('./components/BingoTile.vue')['default']
    EditDialog: typeof import('./components/EditDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveDialog: typeof import('./components/ShareDialog.vue')['default']
    ShareDialog: typeof import('./components/ShareDialog.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
